use Stack_Overflow_Survey;
go


-- Table for 2021 --
CREATE TABLE Bronze.Survey_2021 (
[ResponseId] NVARCHAR (MAX),
[MainBranch] NVARCHAR (MAX),
[Employment] NVARCHAR (MAX),
[Country] NVARCHAR (MAX),
[US_State] NVARCHAR (MAX),
[UK_Country] NVARCHAR (MAX),
[EdLevel] NVARCHAR (MAX),
[Age1stCode] NVARCHAR (MAX),
[LearnCode] NVARCHAR (MAX),
[YearsCode] NVARCHAR (MAX),
[YearsCodePro] NVARCHAR (MAX),
[DevType] NVARCHAR (MAX),
[OrgSize] NVARCHAR (MAX),
[Currency] NVARCHAR (MAX),
[CompTotal] NVARCHAR (MAX),
[CompFreq] NVARCHAR (MAX),
[LanguageHaveWorkedWith] NVARCHAR (MAX),
[LanguageWantToWorkWith] NVARCHAR (MAX),
[DatabaseHaveWorkedWith] NVARCHAR (MAX),
[DatabaseWantToWorkWith] NVARCHAR (MAX),
[PlatformHaveWorkedWith] NVARCHAR (MAX),
[PlatformWantToWorkWith] NVARCHAR (MAX),
[WebframeHaveWorkedWith] NVARCHAR (MAX),
[WebframeWantToWorkWith] NVARCHAR (MAX),
[MiscTechHaveWorkedWith] NVARCHAR (MAX),
[MiscTechWantToWorkWith] NVARCHAR (MAX),
[ToolsTechHaveWorkedWith] NVARCHAR (MAX),
[ToolsTechWantToWorkWith] NVARCHAR (MAX),
[NEWCollabToolsHaveWorkedWith] NVARCHAR (MAX),
[NEWCollabToolsWantToWorkWith] NVARCHAR (MAX),
[OpSys] NVARCHAR (MAX),
[NEWStuck] NVARCHAR (MAX),
[NEWSOSites] NVARCHAR (MAX),
[SOVisitFreq] NVARCHAR (MAX),
[SOAccount] NVARCHAR (MAX),
[SOPartFreq] NVARCHAR (MAX),
[SOComm] NVARCHAR (MAX),
[NEWOtherComms] NVARCHAR (MAX),
[Age] NVARCHAR (MAX),
[Gender] NVARCHAR (MAX),
[Trans] NVARCHAR (MAX),
[Sexuality] NVARCHAR (MAX),
[Ethnicity] NVARCHAR (MAX),
[Accessibility] NVARCHAR (MAX),
[MentalHealth] NVARCHAR (MAX),
[SurveyLength] NVARCHAR (MAX),
[SurveyEase] NVARCHAR (MAX),
[ConvertedCompYearly] NVARCHAR (MAX)
);
go



-- Table for 2022 --
CREATE TABLE Bronze.Survey_2022 (
[ResponseId] NVARCHAR (MAX),
[MainBranch] NVARCHAR (MAX),
[Employment] NVARCHAR (MAX),
[RemoteWork] NVARCHAR (MAX),
[CodingActivities] NVARCHAR (MAX),
[EdLevel] NVARCHAR (MAX),
[LearnCode] NVARCHAR (MAX),
[LearnCodeOnline] NVARCHAR (MAX),
[LearnCodeCoursesCert] NVARCHAR (MAX),
[YearsCode] NVARCHAR (MAX),
[YearsCodePro] NVARCHAR (MAX),
[DevType] NVARCHAR (MAX),
[OrgSize] NVARCHAR (MAX),
[PurchaseInfluence] NVARCHAR (MAX),
[BuyNewTool] NVARCHAR (MAX),
[Country] NVARCHAR (MAX),
[Currency] NVARCHAR (MAX),
[CompTotal] NVARCHAR (MAX),
[CompFreq] NVARCHAR (MAX),
[LanguageHaveWorkedWith] NVARCHAR (MAX),
[LanguageWantToWorkWith] NVARCHAR (MAX),
[DatabaseHaveWorkedWith] NVARCHAR (MAX),
[DatabaseWantToWorkWith] NVARCHAR (MAX),
[PlatformHaveWorkedWith] NVARCHAR (MAX),
[PlatformWantToWorkWith] NVARCHAR (MAX),
[WebframeHaveWorkedWith] NVARCHAR (MAX),
[WebframeWantToWorkWith] NVARCHAR (MAX),
[MiscTechHaveWorkedWith] NVARCHAR (MAX),
[MiscTechWantToWorkWith] NVARCHAR (MAX),
[ToolsTechHaveWorkedWith] NVARCHAR (MAX),
[ToolsTechWantToWorkWith] NVARCHAR (MAX),
[NEWCollabToolsHaveWorkedWith] NVARCHAR (MAX),
[NEWCollabToolsWantToWorkWith] NVARCHAR (MAX),
[OpSysProfessional use] NVARCHAR (MAX),
[OpSysPersonal use] NVARCHAR (MAX),
[VersionControlSystem] NVARCHAR (MAX),
[VCInteraction] NVARCHAR (MAX),
[VCHostingPersonal use] NVARCHAR (MAX),
[VCHostingProfessional use] NVARCHAR (MAX),
[OfficeStackAsyncHaveWorkedWith] NVARCHAR (MAX),
[OfficeStackAsyncWantToWorkWith] NVARCHAR (MAX),
[OfficeStackSyncHaveWorkedWith] NVARCHAR (MAX),
[OfficeStackSyncWantToWorkWith] NVARCHAR (MAX),
[Blockchain] NVARCHAR (MAX),
[NEWSOSites] NVARCHAR (MAX),
[SOVisitFreq] NVARCHAR (MAX),
[SOAccount] NVARCHAR (MAX),
[SOPartFreq] NVARCHAR (MAX),
[SOComm] NVARCHAR (MAX),
[Age] NVARCHAR (MAX),
[Gender] NVARCHAR (MAX),
[Trans] NVARCHAR (MAX),
[Sexuality] NVARCHAR (MAX),
[Ethnicity] NVARCHAR (MAX),
[Accessibility] NVARCHAR (MAX),
[MentalHealth] NVARCHAR (MAX),
[TBranch] NVARCHAR (MAX),
[ICorPM] NVARCHAR (MAX),
[WorkExp] NVARCHAR (MAX),
[Knowledge_1] NVARCHAR (MAX),
[Knowledge_2] NVARCHAR (MAX),
[Knowledge_3] NVARCHAR (MAX),
[Knowledge_4] NVARCHAR (MAX),
[Knowledge_5] NVARCHAR (MAX),
[Knowledge_6] NVARCHAR (MAX),
[Knowledge_7] NVARCHAR (MAX),
[Frequency_1] NVARCHAR (MAX),
[Frequency_2] NVARCHAR (MAX),
[Frequency_3] NVARCHAR (MAX),
[TimeSearching] NVARCHAR (MAX),
[TimeAnswering] NVARCHAR (MAX),
[Onboarding] NVARCHAR (MAX),
[ProfessionalTech] NVARCHAR (MAX),
[TrueFalse_1] NVARCHAR (MAX),
[TrueFalse_2] NVARCHAR (MAX),
[TrueFalse_3] NVARCHAR (MAX),
[SurveyLength] NVARCHAR (MAX),
[SurveyEase] NVARCHAR (MAX),
[ConvertedCompYearly] NVARCHAR (MAX)
);
go



-- Table for 2023 --
CREATE TABLE Bronze.Survey_2023 (
[ResponseId] NVARCHAR (MAX),
[Q120] NVARCHAR (MAX),
[MainBranch] NVARCHAR (MAX),
[Age] NVARCHAR (MAX),
[Employment] NVARCHAR (MAX),
[RemoteWork] NVARCHAR (MAX),
[CodingActivities] NVARCHAR (MAX),
[EdLevel] NVARCHAR (MAX),
[LearnCode] NVARCHAR (MAX),
[LearnCodeOnline] NVARCHAR (MAX),
[LearnCodeCoursesCert] NVARCHAR (MAX),
[YearsCode] NVARCHAR (MAX),
[YearsCodePro] NVARCHAR (MAX),
[DevType] NVARCHAR (MAX),
[OrgSize] NVARCHAR (MAX),
[PurchaseInfluence] NVARCHAR (MAX),
[TechList] NVARCHAR (MAX),
[BuyNewTool] NVARCHAR (MAX),
[Country] NVARCHAR (MAX),
[Currency] NVARCHAR (MAX),
[CompTotal] NVARCHAR (MAX),
[LanguageHaveWorkedWith] NVARCHAR (MAX),
[LanguageWantToWorkWith] NVARCHAR (MAX),
[DatabaseHaveWorkedWith] NVARCHAR (MAX),
[DatabaseWantToWorkWith] NVARCHAR (MAX),
[PlatformHaveWorkedWith] NVARCHAR (MAX),
[PlatformWantToWorkWith] NVARCHAR (MAX),
[WebframeHaveWorkedWith] NVARCHAR (MAX),
[WebframeWantToWorkWith] NVARCHAR (MAX),
[MiscTechHaveWorkedWith] NVARCHAR (MAX),
[MiscTechWantToWorkWith] NVARCHAR (MAX),
[ToolsTechHaveWorkedWith] NVARCHAR (MAX),
[ToolsTechWantToWorkWith] NVARCHAR (MAX),
[NEWCollabToolsHaveWorkedWith] NVARCHAR (MAX),
[NEWCollabToolsWantToWorkWith] NVARCHAR (MAX),
[OpSysPersonal use] NVARCHAR (MAX),
[OpSysProfessional use] NVARCHAR (MAX),
[OfficeStackAsyncHaveWorkedWith] NVARCHAR (MAX),
[OfficeStackAsyncWantToWorkWith] NVARCHAR (MAX),
[OfficeStackSyncHaveWorkedWith] NVARCHAR (MAX),
[OfficeStackSyncWantToWorkWith] NVARCHAR (MAX),
[AISearchHaveWorkedWith] NVARCHAR (MAX),
[AISearchWantToWorkWith] NVARCHAR (MAX),
[AIDevHaveWorkedWith] NVARCHAR (MAX),
[AIDevWantToWorkWith] NVARCHAR (MAX),
[NEWSOSites] NVARCHAR (MAX),
[SOVisitFreq] NVARCHAR (MAX),
[SOAccount] NVARCHAR (MAX),
[SOPartFreq] NVARCHAR (MAX),
[SOComm] NVARCHAR (MAX),
[SOAI] NVARCHAR (MAX),
[AISelect] NVARCHAR (MAX),
[AISent] NVARCHAR (MAX),
[AIAcc] NVARCHAR (MAX),
[AIBen] NVARCHAR (MAX),
[AIToolInterested in Using] NVARCHAR (MAX),
[AIToolCurrently Using] NVARCHAR (MAX),
[AIToolNot interested in Using] NVARCHAR (MAX),
[AINextVery different] NVARCHAR (MAX),
[AINextNeither different nor similar] NVARCHAR (MAX),
[AINextSomewhat similar] NVARCHAR (MAX),
[AINextVery similar] NVARCHAR (MAX),
[AINextSomewhat different] NVARCHAR (MAX),
[TBranch] NVARCHAR (MAX),
[ICorPM] NVARCHAR (MAX),
[WorkExp] NVARCHAR (MAX),
[Knowledge_1] NVARCHAR (MAX),
[Knowledge_2] NVARCHAR (MAX),
[Knowledge_3] NVARCHAR (MAX),
[Knowledge_4] NVARCHAR (MAX),
[Knowledge_5] NVARCHAR (MAX),
[Knowledge_6] NVARCHAR (MAX),
[Knowledge_7] NVARCHAR (MAX),
[Knowledge_8] NVARCHAR (MAX),
[Frequency_1] NVARCHAR (MAX),
[Frequency_2] NVARCHAR (MAX),
[Frequency_3] NVARCHAR (MAX),
[TimeSearching] NVARCHAR (MAX),
[TimeAnswering] NVARCHAR (MAX),
[ProfessionalTech] NVARCHAR (MAX),
[Industry] NVARCHAR (MAX),
[SurveyLength] NVARCHAR (MAX),
[SurveyEase] NVARCHAR (MAX),
[ConvertedCompYearly] NVARCHAR (MAX)
);
go



-- Table for 2024 --
CREATE TABLE Bronze.Survey_2024 (
[ResponseId] NVARCHAR (MAX),
[MainBranch] NVARCHAR (MAX),
[Age] NVARCHAR (MAX),
[Employment] NVARCHAR (MAX),
[RemoteWork] NVARCHAR (MAX),
[Check] NVARCHAR (MAX),
[CodingActivities] NVARCHAR (MAX),
[EdLevel] NVARCHAR (MAX),
[LearnCode] NVARCHAR (MAX),
[LearnCodeOnline] NVARCHAR (MAX),
[TechDoc] NVARCHAR (MAX),
[YearsCode] NVARCHAR (MAX),
[YearsCodePro] NVARCHAR (MAX),
[DevType] NVARCHAR (MAX),
[OrgSize] NVARCHAR (MAX),
[PurchaseInfluence] NVARCHAR (MAX),
[BuyNewTool] NVARCHAR (MAX),
[BuildvsBuy] NVARCHAR (MAX),
[TechEndorse] NVARCHAR (MAX),
[Country] NVARCHAR (MAX),
[Currency] NVARCHAR (MAX),
[CompTotal] NVARCHAR (MAX),
[LanguageHaveWorkedWith] NVARCHAR (MAX),
[LanguageWantToWorkWith] NVARCHAR (MAX),
[LanguageAdmired] NVARCHAR (MAX),
[DatabaseHaveWorkedWith] NVARCHAR (MAX),
[DatabaseWantToWorkWith] NVARCHAR (MAX),
[DatabaseAdmired] NVARCHAR (MAX),
[PlatformHaveWorkedWith] NVARCHAR (MAX),
[PlatformWantToWorkWith] NVARCHAR (MAX),
[PlatformAdmired] NVARCHAR (MAX),
[WebframeHaveWorkedWith] NVARCHAR (MAX),
[WebframeWantToWorkWith] NVARCHAR (MAX),
[WebframeAdmired] NVARCHAR (MAX),
[EmbeddedHaveWorkedWith] NVARCHAR (MAX),
[EmbeddedWantToWorkWith] NVARCHAR (MAX),
[EmbeddedAdmired] NVARCHAR (MAX),
[MiscTechHaveWorkedWith] NVARCHAR (MAX),
[MiscTechWantToWorkWith] NVARCHAR (MAX),
[MiscTechAdmired] NVARCHAR (MAX),
[ToolsTechHaveWorkedWith] NVARCHAR (MAX),
[ToolsTechWantToWorkWith] NVARCHAR (MAX),
[ToolsTechAdmired] NVARCHAR (MAX),
[NEWCollabToolsHaveWorkedWith] NVARCHAR (MAX),
[NEWCollabToolsWantToWorkWith] NVARCHAR (MAX),
[NEWCollabToolsAdmired] NVARCHAR (MAX),
[OpSysPersonal use] NVARCHAR (MAX),
[OpSysProfessional use] NVARCHAR (MAX),
[OfficeStackAsyncHaveWorkedWith] NVARCHAR (MAX),
[OfficeStackAsyncWantToWorkWith] NVARCHAR (MAX),
[OfficeStackAsyncAdmired] NVARCHAR (MAX),
[OfficeStackSyncHaveWorkedWith] NVARCHAR (MAX),
[OfficeStackSyncWantToWorkWith] NVARCHAR (MAX),
[OfficeStackSyncAdmired] NVARCHAR (MAX),
[AISearchDevHaveWorkedWith] NVARCHAR (MAX),
[AISearchDevWantToWorkWith] NVARCHAR (MAX),
[AISearchDevAdmired] NVARCHAR (MAX),
[NEWSOSites] NVARCHAR (MAX),
[SOVisitFreq] NVARCHAR (MAX),
[SOAccount] NVARCHAR (MAX),
[SOPartFreq] NVARCHAR (MAX),
[SOHow] NVARCHAR (MAX),
[SOComm] NVARCHAR (MAX),
[AISelect] NVARCHAR (MAX),
[AISent] NVARCHAR (MAX),
[AIBen] NVARCHAR (MAX),
[AIAcc] NVARCHAR (MAX),
[AIComplex] NVARCHAR (MAX),
[AIToolCurrently Using] NVARCHAR (MAX),
[AIToolInterested in Using] NVARCHAR (MAX),
[AIToolNot interested in Using] NVARCHAR (MAX),
[AINextMuch more integrated] NVARCHAR (MAX),
[AINextNo change] NVARCHAR (MAX),
[AINextMore integrated] NVARCHAR (MAX),
[AINextLess integrated] NVARCHAR (MAX),
[AINextMuch less integrated] NVARCHAR (MAX),
[AIThreat] NVARCHAR (MAX),
[AIEthics] NVARCHAR (MAX),
[AIChallenges] NVARCHAR (MAX),
[TBranch] NVARCHAR (MAX),
[ICorPM] NVARCHAR (MAX),
[WorkExp] NVARCHAR (MAX),
[Knowledge_1] NVARCHAR (MAX),
[Knowledge_2] NVARCHAR (MAX),
[Knowledge_3] NVARCHAR (MAX),
[Knowledge_4] NVARCHAR (MAX),
[Knowledge_5] NVARCHAR (MAX),
[Knowledge_6] NVARCHAR (MAX),
[Knowledge_7] NVARCHAR (MAX),
[Knowledge_8] NVARCHAR (MAX),
[Knowledge_9] NVARCHAR (MAX),
[Frequency_1] NVARCHAR (MAX),
[Frequency_2] NVARCHAR (MAX),
[Frequency_3] NVARCHAR (MAX),
[TimeSearching] NVARCHAR (MAX),
[TimeAnswering] NVARCHAR (MAX),
[Frustration] NVARCHAR (MAX),
[ProfessionalTech] NVARCHAR (MAX),
[ProfessionalCloud] NVARCHAR (MAX),
[ProfessionalQuestion] NVARCHAR (MAX),
[Industry] NVARCHAR (MAX),
[JobSatPoints_1] NVARCHAR (MAX),
[JobSatPoints_4] NVARCHAR (MAX),
[JobSatPoints_5] NVARCHAR (MAX),
[JobSatPoints_6] NVARCHAR (MAX),
[JobSatPoints_7] NVARCHAR (MAX),
[JobSatPoints_8] NVARCHAR (MAX),
[JobSatPoints_9] NVARCHAR (MAX),
[JobSatPoints_10] NVARCHAR (MAX),
[JobSatPoints_11] NVARCHAR (MAX),
[SurveyLength] NVARCHAR (MAX),
[SurveyEase] NVARCHAR (MAX),
[ConvertedCompYearly] NVARCHAR (MAX),
[JobSat] NVARCHAR (MAX)
);
go



-- Table for 2025 --
CREATE TABLE Bronze.Survey_2025 (
[ResponseId] NVARCHAR (MAX),
[MainBranch] NVARCHAR (MAX),
[Age] NVARCHAR (MAX),
[EdLevel] NVARCHAR (MAX),
[Employment] NVARCHAR (MAX),
[EmploymentAddl] NVARCHAR (MAX),
[WorkExp] NVARCHAR (MAX),
[LearnCodeChoose] NVARCHAR (MAX),
[LearnCode] NVARCHAR (MAX),
[LearnCodeAI] NVARCHAR (MAX),
[AILearnHow] NVARCHAR (MAX),
[YearsCode] NVARCHAR (MAX),
[DevType] NVARCHAR (MAX),
[OrgSize] NVARCHAR (MAX),
[ICorPM] NVARCHAR (MAX),
[RemoteWork] NVARCHAR (MAX),
[PurchaseInfluence] NVARCHAR (MAX),
[TechEndorseIntro] NVARCHAR (MAX),
[TechEndorse_1] NVARCHAR (MAX),
[TechEndorse_2] NVARCHAR (MAX),
[TechEndorse_3] NVARCHAR (MAX),
[TechEndorse_4] NVARCHAR (MAX),
[TechEndorse_5] NVARCHAR (MAX),
[TechEndorse_6] NVARCHAR (MAX),
[TechEndorse_7] NVARCHAR (MAX),
[TechEndorse_8] NVARCHAR (MAX),
[TechEndorse_9] NVARCHAR (MAX),
[TechEndorse_13] NVARCHAR (MAX),
[TechEndorse_13_TEXT] NVARCHAR (MAX),
[TechOppose_1] NVARCHAR (MAX),
[TechOppose_2] NVARCHAR (MAX),
[TechOppose_3] NVARCHAR (MAX),
[TechOppose_5] NVARCHAR (MAX),
[TechOppose_7] NVARCHAR (MAX),
[TechOppose_9] NVARCHAR (MAX),
[TechOppose_11] NVARCHAR (MAX),
[TechOppose_13] NVARCHAR (MAX),
[TechOppose_16] NVARCHAR (MAX),
[TechOppose_15] NVARCHAR (MAX),
[TechOppose_15_TEXT] NVARCHAR (MAX),
[Industry] NVARCHAR (MAX),
[JobSatPoints_1] NVARCHAR (MAX),
[JobSatPoints_2] NVARCHAR (MAX),
[JobSatPoints_3] NVARCHAR (MAX),
[JobSatPoints_4] NVARCHAR (MAX),
[JobSatPoints_5] NVARCHAR (MAX),
[JobSatPoints_6] NVARCHAR (MAX),
[JobSatPoints_7] NVARCHAR (MAX),
[JobSatPoints_8] NVARCHAR (MAX),
[JobSatPoints_9] NVARCHAR (MAX),
[JobSatPoints_10] NVARCHAR (MAX),
[JobSatPoints_11] NVARCHAR (MAX),
[JobSatPoints_13] NVARCHAR (MAX),
[JobSatPoints_14] NVARCHAR (MAX),
[JobSatPoints_15] NVARCHAR (MAX),
[JobSatPoints_16] NVARCHAR (MAX),
[JobSatPoints_15_TEXT] NVARCHAR (MAX),
[AIThreat] NVARCHAR (MAX),
[NewRole] NVARCHAR (MAX),
[ToolCountWork] NVARCHAR (MAX),
[ToolCountPersonal] NVARCHAR (MAX),
[Country] NVARCHAR (MAX),
[Currency] NVARCHAR (MAX),
[CompTotal] NVARCHAR (MAX),
[LanguageChoice] NVARCHAR (MAX),
[LanguageHaveWorkedWith] NVARCHAR (MAX),
[LanguageWantToWorkWith] NVARCHAR (MAX),
[LanguageAdmired] NVARCHAR (MAX),
[LanguagesHaveEntry] NVARCHAR (MAX),
[LanguagesWantEntry] NVARCHAR (MAX),
[DatabaseChoice] NVARCHAR (MAX),
[DatabaseHaveWorkedWith] NVARCHAR (MAX),
[DatabaseWantToWorkWith] NVARCHAR (MAX),
[DatabaseAdmired] NVARCHAR (MAX),
[DatabaseHaveEntry] NVARCHAR (MAX),
[DatabaseWantEntry] NVARCHAR (MAX),
[PlatformChoice] NVARCHAR (MAX),
[PlatformHaveWorkedWith] NVARCHAR (MAX),
[PlatformWantToWorkWith] NVARCHAR (MAX),
[PlatformAdmired] NVARCHAR (MAX),
[PlatformHaveEntry] NVARCHAR (MAX),
[PlatformWantEntry] NVARCHAR (MAX),
[WebframeChoice] NVARCHAR (MAX),
[WebframeHaveWorkedWith] NVARCHAR (MAX),
[WebframeWantToWorkWith] NVARCHAR (MAX),
[WebframeAdmired] NVARCHAR (MAX),
[WebframeHaveEntry] NVARCHAR (MAX),
[WebframeWantEntry] NVARCHAR (MAX),
[DevEnvsChoice] NVARCHAR (MAX),
[DevEnvsHaveWorkedWith] NVARCHAR (MAX),
[DevEnvsWantToWorkWith] NVARCHAR (MAX),
[DevEnvsAdmired] NVARCHAR (MAX),
[DevEnvHaveEntry] NVARCHAR (MAX),
[DevEnvWantEntry] NVARCHAR (MAX),
[SOTagsHaveWorkedWith] NVARCHAR (MAX),
[SOTagsWantToWorkWith] NVARCHAR (MAX),
[SOTagsAdmired] NVARCHAR (MAX),
[SOTagsHaveEntry] NVARCHAR (MAX),
[SOTagsWant Entry] NVARCHAR (MAX),
[OpSysPersonal use] NVARCHAR (MAX),
[OpSysProfessional use] NVARCHAR (MAX),
[OfficeStackAsyncHaveWorkedWith] NVARCHAR (MAX),
[OfficeStackAsyncWantToWorkWith] NVARCHAR (MAX),
[OfficeStackAsyncAdmired] NVARCHAR (MAX),
[OfficeStackHaveEntry] NVARCHAR (MAX),
[OfficeStackWantEntry] NVARCHAR (MAX),
[CommPlatformHaveWorkedWith] NVARCHAR (MAX),
[CommPlatformWantToWorkWith] NVARCHAR (MAX),
[CommPlatformAdmired] NVARCHAR (MAX),
[CommPlatformHaveEntr] NVARCHAR (MAX),
[CommPlatformWantEntr] NVARCHAR (MAX),
[AIModelsChoice] NVARCHAR (MAX),
[AIModelsHaveWorkedWith] NVARCHAR (MAX),
[AIModelsWantToWorkWith] NVARCHAR (MAX),
[AIModelsAdmired] NVARCHAR (MAX),
[AIModelsHaveEntry] NVARCHAR (MAX),
[AIModelsWantEntry] NVARCHAR (MAX),
[SOAccount] NVARCHAR (MAX),
[SOVisitFreq] NVARCHAR (MAX),
[SODuration] NVARCHAR (MAX),
[SOPartFreq] NVARCHAR (MAX),
[SO_Dev_Content] NVARCHAR (MAX),
[SO_Actions_1] NVARCHAR (MAX),
[SO_Actions_16] NVARCHAR (MAX),
[SO_Actions_3] NVARCHAR (MAX),
[SO_Actions_4] NVARCHAR (MAX),
[SO_Actions_5] NVARCHAR (MAX),
[SO_Actions_6] NVARCHAR (MAX),
[SO_Actions_9] NVARCHAR (MAX),
[SO_Actions_7] NVARCHAR (MAX),
[SO_Actions_10] NVARCHAR (MAX),
[SO_Actions_15] NVARCHAR (MAX),
[SO_Actions_15_TEXT] NVARCHAR (MAX),
[SOComm] NVARCHAR (MAX),
[SOFriction] NVARCHAR (MAX),
[AISelect] NVARCHAR (MAX),
[AISent] NVARCHAR (MAX),
[AIAcc] NVARCHAR (MAX),
[AIComplex] NVARCHAR (MAX),
[AIToolCurrently partially AI] NVARCHAR (MAX),
[AIToolDon't plan to use AI for this task] NVARCHAR (MAX),
[AIToolPlan to partially use AI] NVARCHAR (MAX),
[AIToolPlan to mostly use AI] NVARCHAR (MAX),
[AIToolCurrently mostly AI] NVARCHAR (MAX),
[AIFrustration] NVARCHAR (MAX),
[AIExplain] NVARCHAR (MAX),
[AIAgents] NVARCHAR (MAX),
[AIAgentChange] NVARCHAR (MAX),
[AIAgent_Uses] NVARCHAR (MAX),
[AgentUsesGeneral] NVARCHAR (MAX),
[AIAgentImpactSomewhat agree] NVARCHAR (MAX),
[AIAgentImpactNeutral] NVARCHAR (MAX),
[AIAgentImpactSomewhat disagree] NVARCHAR (MAX),
[AIAgentImpactStrongly agree] NVARCHAR (MAX),
[AIAgentImpactStrongly disagree] NVARCHAR (MAX),
[AIAgentChallengesNeutral] NVARCHAR (MAX),
[AIAgentChallengesSomewhat disagree] NVARCHAR (MAX),
[AIAgentChallengesStrongly agree] NVARCHAR (MAX),
[AIAgentChallengesSomewhat agree] NVARCHAR (MAX),
[AIAgentChallengesStrongly disagree] NVARCHAR (MAX),
[AIAgentKnowledge] NVARCHAR (MAX),
[AIAgentKnowWrite] NVARCHAR (MAX),
[AIAgentOrchestration] NVARCHAR (MAX),
[AIAgentOrchWrite] NVARCHAR (MAX),
[AIAgentObserveSecure] NVARCHAR (MAX),
[AIAgentObsWrite] NVARCHAR (MAX),
[AIAgentExternal] NVARCHAR (MAX),
[AIAgentExtWrite] NVARCHAR (MAX),
[AIHuman] NVARCHAR (MAX),
[AIOpen] NVARCHAR (MAX),
[ConvertedCompYearly] NVARCHAR (MAX),
[JobSat] NVARCHAR (MAX)
);
go


